### PR TITLE
Use previous orientaion as default orientation

### PR DESCRIPTION
**Pull request by hvorovk**

### CODE REVIEW

**Comment by CODeRUS** [comment]
is this for undefined reading result?

**Comment by hvorovk** [comment]
Yep, fir example on aurora os, when device placed on the table, orientation fall to portrait, but ui of os in another orientation

**Comment by CODeRUS** [comment]
okay, please check rpm from atrifacts: https://github.com/CODeRUS/screencast/actions/runs/10633889193

**Comment by hvorovk** [comment]
Working fine on AuroraOS. Can't check on other system.

**Pull request merged**
